spring:
  datasource:
    url: jdbc:mysql://123.60.48.119:3306/barterdev
    username: barterdev
    password: barterdevABC123
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379

  application:
    name: adservice

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.barter.adservice.domain
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10114/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1


# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
