server:
  port: 10114
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8
spring:
  application:
    name: barter-eureka-server #应用名称，会在Eureka中显示
eureka:
  client:
    register-with-eureka: false #是否注册自己的信息到eureka server，默认是true
    fetch-registry: false #是否拉取其他服务信息，默认true
    service-url: #eureka server的地址，现在是自己的地址，如果是集群，需要加上其他server的地址
      defaultZone: http://localhost:${server.port}/eureka
